### PR TITLE
GTCEu 2.6 and 2.7 split

### PR DESCRIPTION
**Pull request by Nrmot**
GTCEu documentation split for GTCEu 2.6 below and 2.7+

This pull request will update and split Groovyscript GTCEu documentation to 2 different versions.

[WIP]

### CODE REVIEW

**Comment by brachy84** [comment]
I would just make changes to the current docs and state the version instead of splitting it.

**Comment by Rongmario** [comment]
I second that, if you really want to keep the older docs, maybe just adding them in an expandable [admonitions box](https://squidfunk.github.io/mkdocs-material/reference/admonitions).

**Comment by brachy84** [comment]
Whats the status on this?

**Comment by Nrmot** [comment]
I would close this pr, as I have done something else already

**Comment by Nrmot** [comment]
I will probably have another pull request adding example scripts for NTM since someone's forking ntm and making it compatible with Groovyscript, although the chances of it happening is low (and I am going to host my own readthedocs version of groovyscript just for internal purposes, and to test out breaking changes)

**Pull request closed without merging**
